#使用application.yml配置文件将会覆盖默认的properties文件
server:
  tomcat:
    max-connections: 1000
    accesslog:
      enabled: true
    uri-encoding: utf-8
    max-threads: 30

#java -jar xxx.jar --spring.profiles.active=product
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nblocksys?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  mail:
    username: 15599036120@163.com
    password: 320481wht
    host: smtp.163.com
    port: 994
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: false
#打印
logging:
  level:
    com.user.UserMapper: debug
    com.department.DepartmentMapper: debug


#端口
server:
  port: 7891
---
spring:
  profiles: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nblocksys?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
server:
  port: 7892
#打印
logging:
  level:
    com.user.UserMapper: error
---
spring:
  profiles: product
server:
  port: 7893
