server:
  port: 8456
  tomcat:
    max-connections: 1000
    accesslog:
      enabled: true
    #      directory: c:/logs
    uri-encoding: utf-8
    max-threads: 200

loggin:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/page1?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  aop:
    auto: true
    proxy-target-class: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  mail:
    host: smtp.163.com
    port: 994
    username: 15695203200@163.com
    password: 320481wht
    default-encoding: UTF-8
    smtp:
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
    debug: true

